module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "test",
        "chore",
        "revert",
        "build",
        "ci",
        "perf",
        "merge",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "auth",
        "core",
        "common",
        "components",
        "utils",
        "config",
        "mock",
        "views",
        "router",
        "store",
        "styles",
        "assets",
        "plugins",
        "static",
        "public",
        "dist",
        "docs",
        "examples",
        "test",
      ],
    ],
  },
};
